## B"H


###
http://localhost:8000/api/v1/products?offset=5&limit=10&sort=price&order=asc

###
GET http://localhost:8000/api/v1/products/search/the?limit=10&sort=price&order=asc

###
GET http://localhost:8000/api/v1/products/144

###
POST http://localhost:8000/api/v1/products
Content-Type: application/json

{
  "title": "New Product",
  "description": "This is a new product",
  "price": 100,
  "category": "electronics",
  "stock": 50,
  "thumbnail": "https://media-cldnry.s-nbcnews.com/image/upload/t_focal-1000x667,f_auto,q_auto:best/rockcms/2025-04/250403-donald-trump-se-1026a-c954d5.jpg"
}

###
PATCH http://localhost:8000/api/v1/products/1
Content-Type: application/json

{
  "price": 150
}

###
DELETE http://localhost:8000/api/v1/products/1


###
POST http://localhost:8000/api/v1/products/seed

########################
# Users Controller
########################

###
http://localhost:8000/api/v1/users

###
GET http://localhost:8000/api/v1/users/1

###
GET http://localhost:8000/api/v1/users/search/Gonzalez?limit=10&sort=firstName&order=asc

###
POST http://localhost:8000/api/v1/users
Content-Type: application/json

{

}

###
PATCH http://localhost:8000/api/v1/users/1
Content-Type: application/json

{
  "firstName": "Jane",
  "lastName": "Doe"
}

###
DELETE http://localhost:8000/api/v1/users/1

###
POST http://localhost:8000/api/v1/users/seed


########################
# Reviews Controller
########################

###
http://localhost:8000/api/v1/reviews

###
GET http://localhost:8000/api/v1/reviews/720

###
GET http://localhost:8000/api/v1/reviews/search/great?limit=10&sort=rating&order=asc

###
POST http://localhost:8000/api/v1/reviews
Content-Type: application/json

{
"product_id": 250,
  "rating": 2,
  "comment": "Why is everyone so obsessed with kiwis? I can't stand the taste of them. I don't get the hype.",
  "date": "2025-05-23T08:56:21.62",
  "reviewer_name": "Emma Miller",
  "reviewer_email": "emma.miller@x.dummyjson.com",
  "reviewer_id": 5
}

###
PATCH http://localhost:8000/api/v1/reviews/722
Content-Type: application/json

{
  "rating": 4,
  "comment": "I love kiwis! They are so delicious and refreshing. I could eat them every day.",
  "date": "2025-05-28T08:56:21.62"
}

###
DELETE http://localhost:8000/api/v1/reviews/722